### ISSUE TITLE
This JSX tag's 'children' prop expects a single child of type 'Element', but multiple children were provided.

### ISSUE THREAD

**Issue by darccide** [RichardBray/episode-picker-ts#1]
I get the following error if I run your code as it currently is for the Rick and Morty episode picker.
```
This JSX tag's 'children' prop expects a single child of type 'Element', but multiple children were provided.
```
The error points to `index.tsx`. I believe it is an issue with Solid, but I am not entirely sure. If you could shed some light on this issue that would be most appreciated.

**Comment by RichardBray** [comment]
@darccide Very good spot, this is an issue to do with the newer version of Typescript. I have since updated the `index.tsx` file in `master` to this:

```jsx
  <StoreProvider>
    <Router>
      <RouterPage pageComponent={<HomePage />} path='/' />
      <RouterPage pageComponent={<FavPage />} path='/faves' />
    </Router>
  </StoreProvider>
```

And added the `<App />` component to the page itself instead of the router.
